config/routes.rb
Diego::Application.routes.draw do
  
  ##############################################################################
  # site routes
  ##############################################################################
  root :to => "site/home#index"
  
  # site/products controller
  
  get "/produtos(/:page)" => "site/products#index",
    :constraints => {:page => /\d{1,}/}, :as => :products
    
  get "/produtos/:category(/:page)" => "site/products#index",
    :constraints => {:page => /\d{1,}/}, :as => :product_category
    
  get "/produtos/:category/:product" => "site/products#show", :as => :product
  
  
  # site/services controller
  
  get "/servicos(/:page)" => "site/services#index",
    :constraints => {:page => /\d{1,}/}, :as => :services
    
  get "/servicos/:service" => "site/services#show", :as => :service

  # static
  get ":page.html" => "site/static#index", :as => :static
  
  # contact
  get "/contato" => 'site/contact#new', :as => :contact
  post "/contato(.:format)" => 'site/contact#create', :as => :contacts

  ##############################################################################
  # ative admin
  ##############################################################################
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  # http://stackoverflow.com/questions/12645936/how-to-get-the-request-uri-inside-active-admin
  namespace :admin do
    resources :services do
      resources :pictures
    end
  
    resources :products do
      resources :pictures
    end
  end

end

app/controllers/site/contact_controller.rb
class Site::ContactController < SiteController
  respond_to :html, :js
  
  def new
    @contact = Contact.new
    respond_with(@contact)
  end
  
  def create
    @contact = Contact.new(params[:contact])
    
    if @contact.save
      # send an email
      AppMailer.contact_email(@contact).deliver
      
      unless request.xhr?
        flash[:notice] = t('messages.contact.success')
      end
    end
    
    respond_with(@contact, :location => contacts_path)
  end
end

app/controllers/site/home_controller.rb
class Site::HomeController < SiteController
  caches_page :index
  
  def index
  end
end

app/controllers/site/products_controller.rb
# encoding: UTF-8

class Site::ProductsController < SiteController
  caches_page :show, :index
  
  respond_to :html
  
  # /produtos(/:page)
  # /produtos/:category(/:page)
  def index
    @products = Product.enabled
    
    if params[:category].present?
      category = Category.find_by_slug(params[:category])
      raise_404("Categoria não encontrada") unless category
      @products = @products.where(:category_id => category.id)
    end
    
    @products = @products.page(params[:page]).per(params[:per])
    respond_with(@products)
  end

  # /produtos/:category/:product
  def show
    @product = Product.enabled.find_by_slug(params[:product])
    
    raise_404("Produto não encontrado") unless @product

    respond_with(@product)
  end
end

app/controllers/site/services_controller.rb
# encoding: UTF-8

class Site::ServicesController < SiteController
  caches_page :index, :show
  
  respond_to :html
  
  def index
    @services = Service.enabled.page(params[:page]).per(params[:per])
    respond_with(@services)
  end

  def show
    @service = Service.enabled.find_by_slug(params[:service])
    
    raise("Serviço não encontrado") unless @service
    
    respond_with(@service)
  end
end

app/controllers/site/static_controller.rb
class Site::StaticController < SiteController
  def index
    template = Rails.root.join("app","views","site","static","#{params[:page]}.html.erb")
    if File.exists?(template)
      render params[:page]
    else
      raise_404
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
end

app/helpers/site/contact_helper.rb
module Site::ContactHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
  def home_products
    Product.enabled.on_home_page
  end
  
  def home_services
    Service.enabled.on_home_page
  end
  
  def home_video
    product = home_products.where('video IS NOT NULL AND video != ""').first

    unless product.nil? || product.video.nil? || product.video.empty?
      video = content_tag('iframe', nil, {
        :width => 420,
        :height => 315,
        :src => "http://www.youtube.com/embed/#{product.video}?rel=0&controls=2&showinfo=0&theme=light&=1",
        :frameborder => 0,
        :allowfullscreen => :allowfullscreen
      })
      description = simple_format(product.video_description)
      link = link_to("Veja Mais", product_path(product), class: 'read-more', alt: 'Veja Mais')

      content_tag(:article, video + description + link, class: 'home-video')
    end
  end
end

app/helpers/site/pictures_helper.rb
module Site::PicturesHelper
  def picture(picture, size = :original, options = {})
    if picture
      options.merge({:alt => picture.title, :title => picture.title})
      image_tag(picture.file.url(size), options)
    else
      image_tag("default_#{size}.jpg", options)
    end
  end
end

app/helpers/site/products_helper.rb
module Site::ProductsHelper
  def product_path(product)
    super({:category => product.category.slug, :product => product.slug} )
  end
end

app/helpers/site/services_helper.rb
module Site::ServicesHelper
  def service_path(service)
    super(:service => service.slug)
  end
end

app/helpers/site/snippet_helper.rb
module Site::SnippetHelper
  def snippet(slug = nil)
    @snippets ||= {}
    @snippets[slug] ||= Snippet.find_by_slug(slug).try(:content) || slug
  end
end

app/helpers/site/static_helper.rb
module Site::StaticHelper
  def static(page)
    "#{page}.html"
  end
end

app/views/site/header.html.erb
<div class="full-width-wrapper" id="header">
  <div class="full-width-wrapper" id="abstract-bg">
      <!--Banner-->
      <div class="fixed-width-wrapper" id="banner">
          <a href="/" title="" class="logo">
              <img src="/assets/logo.png" alt="Maxx - The Modern HTML template">
          </a>
    

      <!--Get in touch-->
         
           
              <div id="get-in-touch">
                  <div class="via-phone-number float-left">
                      <a title="Keep in touch with us" class="icon sprite float-left">Keep in touch with us</a>
                      <h2>Fale conosco por telefone: 
                          <strong>51 3566 8992</strong>
                      </h2>
                      <span>Ou <a href="/contato" title="">mande um e-mail</a> para solicitar o nosso contato. 
                      </span>
                  </div>
                  
              </div>
          
          
      <!--/Get in touch-->    
      </div>
      <!--/Banner-->
      <!--Navigation + Search-->
      <div class="fixed-width-wrapper border-radius-5px" id="navigation-bar">
          <div id="g-navigation">
              <ul class="simple-drop-down-menu">
                  <li class="home-page border-radius-left-5px <%= 'current' if simple_menu.active == :home %>">
                      <a href="/">Home</a>
                  </li>
                  <li class="<%= 'current' if simple_menu.active == :about %>">
                      <a href="<%= static_path('sobre-a-empresa') %>" title="">Empresa</a>
                  </li>
                  <li class="<%= 'current' if simple_menu.active == :products %>">
                    <a href="<%= products_path() %>" title="">Produtos</a>
                  </li>
                  <li class="<%= 'current' if simple_menu.active == :services %>">
                    <a href="<%= services_path() %>" title="">Serviços</a>
                  </li>
                  <li class="<%= 'current' if simple_menu.active == :contact %>">
                      <a href="<%= contacts_path() %>" title="">Contato</a>
                  </li>
              </ul>
          </div>
          <!--
          <div id="g-search">
              <form action="" method="post">
                  <div>
                      <input type="text" class="input-field border-radius-left-3px reset-text" value="Pesquise aqui...">
                  </div>
                  <div>
                      <button type="submit" title="Pesquisar" class="sprite">
                          <em>Pesquisar</em>
                      </button>
                  </div>
              </form>
          </div>
      </div>
      -->
      <!--/Navigation + Search-->
  </div>
</div>